apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: oa9o9nr1n-go 
  janus-idp.io/tekton: oa9o9nr1n-go
  backstage.io/kubernetes-id: oa9o9nr1n-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oa9o9nr1n-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml